# Generated by Django 4.2.13 on 2025-12-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_entry_mood_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('breath', 'Respiración Consciente'), ('meditation', 'Meditación'), ('diary', 'Diario Emocional'), ('grounding', 'Grounding'), ('reflection', 'Reflexión'), ('calm', 'Calma'), ('sos', 'Recurso SOS')], max_length=20, unique=True)),
                ('flower_name', models.CharField(max_length=50)),
                ('flower_emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Flower Type',
                'verbose_name_plural': 'Flower Types',
            },
        ),
        migrations.CreateModel(
            name='GardenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plants', models.IntegerField(default=0)),
                ('current_month_plants', models.IntegerField(default=0)),
                ('total_mindful_minutes', models.IntegerField(default=0)),
                ('current_gentle_streak', models.IntegerField(default=0)),
                ('longest_gentle_streak', models.IntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('garden_started', models.DateTimeField(auto_now_add=True)),
                ('last_reset_month', models.IntegerField(default=0)),
                ('last_reset_year', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garden', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garden Profile',
                'verbose_name_plural': 'Garden Profiles',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.CharField(choices=[('seed', 'Semilla'), ('sprout', 'Brote'), ('growing', 'Creciendo'), ('blooming', 'Floreciendo')], default='seed', max_length=10)),
                ('times_watered', models.IntegerField(default=1)),
                ('planted_date', models.DateTimeField(auto_now_add=True)),
                ('bloomed_date', models.DateTimeField(blank=True, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('flower_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flowertype')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.gardenprofile')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['-planted_date'],
            },
        ),
        migrations.CreateModel(
            name='WellnessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('breath', 'Respiración'), ('meditation', 'Meditación'), ('diary', 'Diario'), ('grounding', 'Grounding'), ('reflection', 'Reflexión'), ('calm', 'Calma'), ('sos', 'SOS')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.gardenprofile')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plant')),
            ],
            options={
                'verbose_name': 'Wellness Activity',
                'verbose_name_plural': 'Wellness Activities',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('first_plant', 'Primera Planta'), ('first_bloom', 'Primera Flor'), ('7_days', '7 Días de Práctica'), ('15_days', '15 Días de Práctica'), ('30_days', '30 Días de Práctica'), ('10_plants', '10 Plantas'), ('25_plants', '25 Plantas'), ('50_plants', '50 Plantas'), ('100_plants', '100 Plantas'), ('all_flowers', 'Todas las Flores'), ('1_hour', '1 Hora de Autocuidado'), ('10_hours', '10 Horas de Autocuidado'), ('garden_month', 'Un Mes de Jardín')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.gardenprofile')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['-achieved_at'],
                'unique_together': {('garden', 'milestone_type')},
            },
        ),
    ]
